services:
  - type: web
    name: serenity-fastapi
    rootDir: backend
    env: docker
    plan: free
    region: singapore
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: '["
serenity-lead-mase2025ai-8394s-projects.vercel.app","http://localhost:5173"]'
